config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
#from config.views import main
from config.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', main),
    path("", index),
    path("users/", include("users.urls")),
    path("posts/", include("posts.urls"))
]

urlpatterns += static(
    prefix= settings.MEDIA_URL,
document_root = settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from posts.views import feeds, comment_add, comment_delete, post_add, tags

app_name = "posts"
urlpatterns = [
    path("feeds/", feeds, name="feeds"),
    path("comment_add/", comment_add, name="comment_add"),
    path("comments/<int:comment_id>/delete/", comment_delete, name="comment_delete"),
    path("post_add/", post_add, name="post_add"),
    path("tags/<str:tag_name>/", tags, name="tags"),
]

users/urls.py
from django.urls import path
from users.views import login_view, logout_view, signup

app_name = 'users'
urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup, name='signup'),
]

posts/models.py
from django.db import models
from django.db.models import ManyToManyField
from django.forms import CheckboxSelectMultiple

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시",auto_now_add=True)

class PostImage(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name="포스트",
        on_delete=models.CASCADE,
    )
    photo = models.ImageField("사진",upload_to="post")
class Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시", auto_now_add=True)

class HashTag(models.Model):
    name = models.CharField("태그명", max_length= 50)

    def __str__(self):
        return self.name


    tag = models.ManyToManyField("posts.HashTag", verbose_name="해시태그 목록", blank=True)

posts/forms.py
from django import forms

from posts.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "post",
            "content",
        ]
        widgets = {
            "content": forms.Textarea(
                attrs={
                    "placeholder": "댓글 달기...",
                }
            )
        }

posts/views.py
from django.http import (
    HttpResponseBadRequest,
    HttpResponseRedirect,
    HttpResponseForbidden,
)
from django.shortcuts import render, redirect
from django.urls import reverse

from posts.forms import CommentForm, PostForm
from posts.models import Post, Comment, PostImage


def feeds(request):
    user = request.user
    if not user.is_authenticated:
        return redirect("users:login")

    posts = Post.objects.all()
    comment_form = CommentForm()
    context = {
        "posts": posts,
        "comment_form": comment_form,
    }
    return render(request, "posts/feeds.html", context)


# 댓글 작성을 처리할 View
def comment_add(request):
    if request.method == "GET":
        # 이 View에 GET요청이 전달되면, 잘못된 요청임을 브라우저에 알려준다.
        return HttpResponseBadRequest()

    # request.POST로 전달된 데이터를 사용해 CommentForm인스턴스를 생성
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # commit=False옵션으로 메모리상에 Comment객체 생성
        comment = form.save(commit=False)

        # Comment생성에 필요한 사용자정보를 request에서 가져와 할당
        comment.user = request.user

        # DB에 Comment객체 저장
        comment.save()

        # 생성된 Comment의 정보 확인
        print(comment.id)
        print(comment.content)
        print(comment.user)

        # 생성한 comment에서 연결된 post정보를 가져와서 id값을 사용
        url = reverse("posts:feeds") + f"#post-{comment.post.id}"
        return HttpResponseRedirect(url)


def comment_delete(request, comment_id):
    if request.method == "POST":
        comment = Comment.objects.get(id=comment_id)
        if comment.user == request.user:
            comment.delete()
            url = reverse("posts:feeds") + f"#post-{comment.post.id}"
            return HttpResponseRedirect(url)
        else:
            return HttpResponseForbidden("이 댓글을 삭제할 권한이 없습니다")
    else:
        # 이 View에 오는 GET요청은 잘못되었다고 브라우저에 돌려준다
        return HttpResponseBadRequest()


def post_add(request):
    if request.method == "POST":
        # request.POST로 온 데이터 ("content")는 PostForm으로 처리
        form = PostForm(request.POST)

        if form.is_valid():
            # Post의 "user"값은 request에서 가져와 자동할당한다
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            # Post를 생성 한 후
            # request.FILES.getlist("images")로 전송된 이미지들을 순회하며 PostImage객체를 생성한다
            for image_file in request.FILES.getlist("images"):
                # request.FILES또는 request.FILES.getlist()로 가져온 파일은
                # Model의 ImageField부분에 곧바로 할당한다
                PostImage.objects.create(
                    post=post,
                    photo=image_file,
                )

            # 모든 PostImage와 Post의 생성이 완료되면
            # 피드페이지로 이동하여 생성된 Post의 위치로 스크롤되도록 한다
            url = reverse("posts:feeds") + f"#post-{post.id}"
            return HttpResponseRedirect(url)

    # GET요청일 때는 빈 form을 보여주도록 한다
    else:
        form = PostForm()

    context = {"form": form}
    return render(request, "posts/post_add.html", context)

templates/posts/feeds.html
{% extends 'base.html' %}

{% block content %}
<nav>
    <h1>
        <a href="{% url 'posts:feeds' %}">Pystagram</a>
    </h1>
    <a href="{% url 'posts:post_add' %}">Add Post</a>
    <a href="{% url 'users:logout' %}">Logout</a>
</nav>
<div id="feeds" class="post-container">
    <!-- 전달된 Post QuerySet객체를 순회 -->
    {% for post in posts %}
    <article class="post">
        <header class="post-header">
            {% if post.user.profile_image %}
                <img src="{{ post.user.profile_image.url }}">
            {% endif %}
            <span>{{ post.user.username }}</span>
        </header>

        <!-- 이미지 슬라이드 영역 시작 -->
        <div class="post-images splide">
            <div class="splide__track">
                <ul class="splide__list">
                    {% for image in post.postimage_set.all %}
                        {% if image.photo %}
                            <li class="splide__slide">
                                <img src="{{ image.photo.url }}">
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
        <!-- 이미지 슬라이드 영역 종료 -->

        <div class="post-content">
            {{ post.content|linebreaksbr }}
        </div>

        <div class="post-buttons">
            <button>Likes(0)</button>
            <span>Comments(0)</span>
        </div>

        <div class="post-comments">
            <ul>
                <!-- 각 Post에 연결된 PostComment들을 순회 -->
                {% for comment in post.comment_set.all %}
                    <li>
                        <span>{{ comment.user.username }}</span>
                        <span>{{ comment.content }}</span>

                        {% if user == comment.user %}
                         <form method="POST" action="{% url 'posts:comment_delete' comment_id = comment.id %}">
                             {% csrf_token% %}
                             <button type="submit">삭제</button>
                         </form>
                    </li>
                {% endfor %}
            </ul>
        </div>

        <small>{{ post.created }}</small>
        <div class="post-comment-create">
           <form method="POST" action="{% url 'posts:comment_add' %}">
               {% csrf_token% %}
               {{ comment_form.content }}
               <button type="submit">게시</button>
           </form>
        </div>
    </article>
    {% endfor %}
</div>

<!-- Splide 초기화 자바스크립트 코드 -->
<script>
    const elms = document.getElementsByClassName('splide');
    for (let i = 0; i < elms.length; i++) {
        new Splide(elms[i]).mount();
    }
</script>
{% endblock %}

templates/posts/post_add.html
{% extends 'base.html' %}

{% block content %}
<nav>
    <h1>
        <a href="{% url 'posts:feeds' %}">Pystagram</a>
    </h1>
    <!-- 로그아웃 링크도 함께 추가 -->
    <a href="{% url 'users:logout' %}">Logout</a>
</nav>
<div id="container">
    <div id="post-add">
        <h1>Post 작성</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                <!-- label의 for속성에는 가리키는 input의 id값을 입력 -->
                <label for="id_images">이미지</label>
                <input id="id_images" name="images" type="file" multiple>
            </div>
            {{ form.as_p }}
            <button type="submit">게시</button>
        </form>
    </div>
</div>
{% endblock %}

templates/posts/tags.html
{% extends 'base.html' %}

{% block content %}
<nav>
    <h1>
        <a href="{% url 'posts:feeds' %}">Pystagram</a>
    </h1>
    <a href="{% url 'posts:post_add' %}">Add post</a>
    <a href="{% url 'users:logout' %}">Logout</a>
</nav>
<div id="tags">
    <header class="tags-header">
        <h2>#{{ tag_name }}</h2>
        <div>게시물 {{ posts.count }}</div>
    </header>
    <div class="post-grid-container">
        {% for post in posts %}
            {# Post에 연결된 PostImage가 있으며, 연결된 첫 번째 PostImage의 photo가 비어있지 않은 경우 #}

            {% if post.postimage_set.first and post.postimage_set.first.photo %}
                <div class="post-grid">
                    <img src="{{ post.postimage_set.first.photo.url }}">
                </div>
            {% endif %}
        {% empty %}
            <p>검색된 게시물이 없습니다</p>
        {% endfor %}
    </div>
</div>
{% endblock %}